# Generated by Django 4.2.16 on 2024-11-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_remove_depositmodel_rsrv_type_nm_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deposit',
            field=models.ManyToManyField(null=True, to='fin.depositmodel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saving',
            field=models.ManyToManyField(null=True, to='fin.savingmodel'),
        ),
    ]
